-- 001_create_os_db.sql
-- 사용자 및 게임 기록 테이블(메인 서버 관리)

CREATE TABLE IF NOT EXISTS users (userID VARCHAR(255) PRIMARY KEY, nickname VARCHAR(255), email VARCHAR(255));
CREATE TABLE IF NOT EXISTS userItems (itemID INT PRIMARY KEY, userID VARCHAR(255));
CREATE TABLE IF NOT EXISTS userTitles (titleID INT PRIMARY KEY, userID VARCHAR(255));
CREATE TABLE IF NOT EXISTS matchCodeHistory (historyID INT PRIMARY KEY, userID VARCHAR(255), code TEXT);
CREATE TABLE IF NOT EXISTS rooms (roomID INT PRIMARY KEY, title VARCHAR(255));
CREATE TABLE IF NOT EXISTS roomParticipants (participantID INT PRIMARY KEY, roomID INT, userID VARCHAR(255));
CREATE TABLE IF NOT EXISTS problems (problemID INT PRIMARY KEY, title VARCHAR(255));
CREATE TABLE IF NOT EXISTS matches (matchID INT PRIMARY KEY, roomID INT);
CREATE TABLE IF NOT EXISTS matchProbles (matchProblemID INT PRIMARY KEY, matchID INT); --[cite: 2] 원문 오타 반영
CREATE TABLE IF NOT EXISTS matchSubmissions (submissionID INT PRIMARY KEY, matchProblemID INT);
CREATE TABLE IF NOT EXISTS matchRankings (rankingID INT PRIMARY KEY, matchID INT);
CREATE TABLE IF NOT EXISTS friends (friendID INT PRIMARY KEY, userID VARCHAR(255));
CREATE TABLE IF NOT EXISTS reviewInvites (inviteID INT PRIMARY KEY, userID VARCHAR(255));